version: '3'
services:
  backend:
    build: ./backend
    container_name: appartement_manager_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    image: nginx:alpine
    container_name: appartement_manager_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
