version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Assurez-vous que c'est 'Dockerfile' avec un "d" minuscule
    ports:
      - "5000:5000"
  
  frontend:
    build:  # Construire l'image à partir du Dockerfile dans le répertoire frontend
      context: ./frontend
      dockerfile: Dockerfile  # Assurez-vous que le nom est correct
    ports:
      - "80:80"
