version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Assurez-vous que c'est 'Dockerfile' avec un "D" majuscule
    ports:
      - "5000:5000"
  
  frontend:
    build:  # Construire l'image à partir du Dockerfile dans le répertoire frontend
      context: ./frontend
      dockerfile: Dockerfile  # Remplacez par le nom correct si différent
    ports:
      - "80:80"
