# backend/Dockerfile
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier des dépendances
COPY requirements.txt requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code de l'application
COPY . .

# Définir la commande pour démarrer l'application
CMD ["python", "app.py"]  # Assure-toi que 'app.py' est le bon point d'entrée
